"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const body_parser_1 = __importDefault(require("body-parser"));
require("./Database/Sequelize");
const UsersController_1 = require("./task/infraestructure/controllers/UsersController");
const PostgresUsersRepository_1 = require("./task/infraestructure/repositories/PostgresUsersRepository");
const UserServie_1 = require("./task/aplication/services/user-cases/UserServie");
const DirectionsController_1 = require("./task/infraestructure/controllers/DirectionsController");
const PostgresDirectionRepository_1 = require("./task/infraestructure/repositories/PostgresDirectionRepository");
const DirectionService_1 = require("./task/aplication/services/user-cases/DirectionService");
const app = (0, express_1.default)();
const PORT = process.env.PORT || 3000;
app.use(body_parser_1.default.json());
const userRepository = new PostgresUsersRepository_1.PostgresUserRepository();
const userService = new UserServie_1.UserService(userRepository);
const usersController = new UsersController_1.UsersController(userService);
const directionRepository = new PostgresDirectionRepository_1.PostgresDirectionsRepository();
const directionService = new DirectionService_1.DirectionService(directionRepository);
const directionController = new DirectionsController_1.DirectionsController(directionService);
app.post('/api/v1/users', (req, res) => usersController.registerUser(req, res));
app.post('/api/v1/userslogin', (req, res) => usersController.loginUser(req, res));
app.delete('/api/v1/delete/:email', (req, res) => usersController.deleteUser(req, res));
app.post('/api/v2/directions', (req, res) => directionController.createDirection(req, res));
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
